version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    container_name: messaggio.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      app_net_messaggio:
        ipv4_address: 10.18.0.10

  kafka:
    image: confluentinc/cp-kafka:5.1.2
    container_name: messaggio.kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      app_net_messaggio:
        ipv4_address: 10.18.0.20

  psql-write:
    image: bitnami/postgresql:latest
    restart: always
    container_name: messaggio.psql-write
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 127.0.0.1:${POSTGRESQL_WRITE_PORT}:5432
    volumes:
      - ./volumes/psql-write:/bitnami/postgresql:z
    networks:
      app_net_messaggio:
        ipv4_address: 10.18.0.30

  pgadmin:
    image: dpage/pgadmin4
    container_name: messaggio.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 127.0.0.1:${PGADMIN_PORT}:80
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      app_net_messaggio:
        ipv4_address: 10.18.0.40


networks:
  app_net_messaggio:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.18.0.0/16